/**
 * Vendor the web fonts into public/fonts so the site serves them itself.
 *
 * Run manually when a face or weight range changes:
 *   node scripts/fetch-fonts.cjs
 *
 * It asks Google Fonts for the same css2 URLs the site used to link, with a
 * modern browser UA so the reply is woff2, downloads every file, and rewrites
 * the @font-face rules to point at /fonts/. Two stylesheets come out:
 *
 *   public/fonts/fonts.css     the five reading/UI faces, linked from index.html
 *   public/fonts/atkinson.css  the dyslexia-friendly face, injected on demand
 *
 * Only the latin and latin-ext unicode ranges are kept — the other ranges
 * Google serves (cyrillic, greek, vietnamese) would be dead weight. latin-ext
 * is NOT optional despite the book being English and French: the content uses
 * œ plus the macron and caron letters in Indigenous-language words (ā, ȟ, ē,
 * ū), which live in that range. Dropping it would break exactly the words this
 * book can least afford to render wrong.
 *
 * Inter is fetched upright-only. Its italic is 221 kB and nothing uses it: the
 * italic in this app is Playfair, Source Serif, or Caveat, and the one
 * unfamilied italic inherits body, which index.html sets to Source Serif.
 */
const fs = require("fs");
const path = require("path");
const https = require("https");

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const OUT_DIR = path.join(__dirname, "..", "public", "fonts");
const KEEP_RANGES = ["latin", "latin-ext"];

const SHEETS = {
  "fonts.css": [
    "Playfair+Display:ital,wght@0,400..900;1,400..900",
    "Source+Serif+4:ital,opsz,wght@0,8..60,300..700;1,8..60,300..700",
    "JetBrains+Mono:wght@400..800",
    "Inter:opsz,wght@14..32,300..800",
    "Caveat:wght@400",
  ],
  "atkinson.css": ["Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700"],
};

function get(url, binary = false) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { "User-Agent": UA } }, (res) => {
        if (res.statusCode !== 200) return reject(new Error(`${res.statusCode} for ${url}`));
        const chunks = [];
        res.on("data", (c) => chunks.push(c));
        res.on("end", () => resolve(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString("utf8")));
      })
      .on("error", reject);
  });
}

(async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  let totalBytes = 0;
  let totalFiles = 0;

  for (const [sheetName, families] of Object.entries(SHEETS)) {
    const url =
      "https://fonts.googleapis.com/css2?" +
      families.map((f) => `family=${f}`).join("&") +
      "&display=swap";
    const css = await get(url);

    // Google emits one @font-face per family+range, each preceded by a
    // /* range */ comment. Keep only the ranges we serve.
    const blocks = css.split(/(?=\/\*\s*[a-z-]+\s*\*\/)/g).filter(Boolean);
    const kept = [];

    for (const block of blocks) {
      const rangeMatch = block.match(/\/\*\s*([a-z-]+)\s*\*\//);
      const range = rangeMatch ? rangeMatch[1] : null;
      if (!range || !KEEP_RANGES.includes(range)) continue;

      let out = block;
      const urls = [...block.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]);
      for (const fileUrl of urls) {
        const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || "font";
        const style = /font-style:\s*italic/.test(block) ? "italic" : "normal";
        // Weight belongs in the name: static faces ship one file per weight,
        // and without it Atkinson's 400 and 700 collided on the same filename —
        // each overwrote the other and half the @font-face rules pointed at the
        // wrong file. Variable faces give a range like "300 800", which
        // flattens to a distinct-enough token.
        const weight = ((block.match(/font-weight:\s*([\d\s]+);/) || [])[1] || "400").trim();
        const name =
          `${family}-${range}-${style}-${weight}`.toLowerCase().replace(/[^a-z0-9]+/g, "-") +
          path.extname(new URL(fileUrl).pathname);
        const buf = await get(fileUrl, true);
        fs.writeFileSync(path.join(OUT_DIR, name), buf);
        totalBytes += buf.length;
        totalFiles++;
        out = out.replace(fileUrl, `/fonts/${name}`);
        console.log(`  ${name}  ${(buf.length / 1024).toFixed(1)} kB`);
      }
      kept.push(out.trim());
    }

    const header =
      `/* Generated by scripts/fetch-fonts.cjs — do not hand-edit.\n` +
      `   Self-hosted so the site makes no third-party font requests.\n` +
      `   Ranges: ${KEEP_RANGES.join(", ")}. */\n\n`;
    fs.writeFileSync(path.join(OUT_DIR, sheetName), header + kept.join("\n\n") + "\n");
    console.log(`${sheetName}: ${kept.length} @font-face rules`);
  }

  console.log(`\n${totalFiles} files, ${(totalBytes / 1024).toFixed(0)} kB total`);
})();
